### ISSUE TITLE
Deprecated Git url in docu

### ISSUE THREAD

**Issue by schmocker** [cim-iec/cimpy#20]
The 2 Git urls in you current doc point to the deprecated GitLab repo, see: http://sogno.energy/cimpy/Install.html 

please change docu [here](https://github.com/sogno-platform/cimpy/blob/master/documentation/Install.rst)

**Comment by schmocker** [comment]
resolved in pr #21, waiting for pr to be completed

**Comment by stv0g** [comment]
Fixed
