### ISSUE TITLE
TypeError Exception when importing dynamic data of Synchronous Machines

### ISSUE THREAD

**Issue by martinmoraga** [cim-iec/cimpy#23]
The parameter inertia of the class RotatingMachineDynamics is initialized in the contructor as an integer ([see here](https://github.com/sogno-platform/cimpy/blob/b49972e3c4d5b2d313ec5fd3bcb6c5fcd718d586/cimpy/cgmes_v2_4_15/RotatingMachineDynamics.py#L31C36-L31C40)).

When importing dynamic data, cimimport is converting the values of the cim files using the default value of the cimpy classes. That means, that cimimport tries to read the parameter _inertia_ fro the CIM files as an integer and not as a float which traslante into an exception when reading dynamic data of cim topologies ([see here](https://github.com/sogno-platform/cimpy/blob/817aeb2959b0d1644473013beccaed1709fc02c0/cimpy/cimimport.py#L268C44-L268C45))

The same bahaviour can be observed in the class [SynchronousMachineTimeConstantReactance](https://github.com/sogno-platform/cimpy/blob/b49972e3c4d5b2d313ec5fd3bcb6c5fcd718d586/cimpy/cgmes_v2_4_15/SynchronousMachineTimeConstantReactance.py#L47). The parameters _tpdo_, _tppdo_, _tpqo_, _tppqo_, _tc_ should be initialized as floats in the contructor of the class.

**Comment by m-mirz** [comment]
solved in #39
