### ISSUE TITLE
Small error when calling function cimexport

### ISSUE THREAD

**Issue by martinmoraga** [cim-iec/cimpy#25]
Sometimes when using the funcion `cimexport` a KeyError Exception  occurs

**Comment by stv0g** [comment]
Hi @martinmoraga,

I am wondering, why is this issue closed when the associated PR has not been merged yet? Or are the two unrelated?

**Comment by martinmoraga** [comment]
> Hi @martinmoraga,
> 
> I am wondering, why is this issue closed when the associated PR has not been merged yet? Or are the two unrelated?

Hi @stv0g 

To be honest I dont know why this PR is closed... Now it is open again ;)

**Comment by m-mirz** [comment]
Solved in #39
