### ISSUE TITLE
Many cgmes_v2_4_15 classes are missing when installed with pip.

### ISSUE THREAD

**Issue by SystemsPurge** [cim-iec/cimpy#28]
### Describe the bug

When installing CIMPY using pip, not all the cgmes_v2 classes are present. However using the install script in the repo yields the correct files.

### Steps to reproduce

```shell
pip install cimpy
```
### Expected behavior

All `cgmes_v2` classes are present under the `cimpy/cgmes_v2_4_15` folder , in `/usr/local/lib/python3.7/site-packages`

### Screenshots

![grafik](https://github.com/sogno-platform/cimpy/assets/126253836/dbecc3fa-83ac-403f-8458-2ceaabd515e8)
![grafik](https://github.com/sogno-platform/cimpy/assets/126253836/f875f810-862c-45a4-8859-db653ee6ed19)

### Setup

Using a python:3.7 docker container under WSL on a windows operating system.

**Comment by stv0g** [comment]
Hi @SystemsPurge,

which classes are you missing?

I think I can not reproduce this issue on my system:

```shell
SteffenVogel@GER-L-06044 MINGW64
$ cd .venv/Lib/site-packages/cimpy/cgmes_v2_4_15/
SteffenVogel@GER-L-06044 /.venv/Lib/site-packages/cimpy/cgmes_v2_4_15 (OUDS-3134-cim-cgmes)
$ ls -l | wc -l
486
```

Where I have 486 files inside the `cgmes_v2_4_15` package.

**Comment by SystemsPurge** [comment]
Hello @stv0g 
Well how are you installing it ? i do a simple pip install inside my venv , and i get only 441 classes : 
![grafik](https://github.com/sogno-platform/cimpy/assets/126253836/3af3fae9-55d1-436d-9003-420e55c4a9d0)

**Comment by stv0g** [comment]
Okay, I've build a new package based on the latest master. This package contains the correct number of classes in `cimpy.cgmes_v2_4_15`. So this must have been a mistake when releasing the last cimpy package to PyPi.org.

I will release v1.1.0 as soon as #36 and possibly also #31 are completed.

/cc @m-mirz

**Comment by stv0g** [comment]
A new version has been tagged: https://pypi.org/project/cimpy/1.1.0/

This version has 485 classes:

```shell
$ wget https://files.pythonhosted.org/packages/c0/e9/a98a0bbe7eb08761735f99cebf9efa2044a1c1eb1a1ba06728a701a12ee2/cimpy-1.1.0-py3-none-any.whl
$ unzip cimpy-1.1.0-py3-none-any.whl
$ ls -l cimpy/cgmes_v2_4_15 | wc -l
485
```
