### ISSUE TITLE
Relicense cimpy

### ISSUE THREAD

**Issue by m-mirz** [cim-iec/cimpy#31]
It would be great to align the cimpy license with cimgen. The Apache 2 license facilitates commercial use of the library and contributions.

Please let me know if you approve this motion to relicense cimpy under Apache 2.

- [x] @jounathaen 
- [x] @dinkelbachjan 
- [x] @stv0g 
- [x] @richardmarston 
- [x] @martinmoraga 
- [ ] @schmocker 
- [ ] @SimonGrimmACS

**Comment by stv0g** [comment]
I support a change of cimpy's license to Apache-2.0

**Comment by jounathaen** [comment]
Fine for me

**Comment by dinkelbachjan** [comment]
I agree to relicense cimpy under Apache 2.

**Comment by martinmoraga** [comment]
That is fine for me

**Comment by richardmarston** [comment]
Ich geb' meine Erlaubnis heut' frei,
Cimpy wird Apache, so sei.
Neue Lizenz, hurra,
Für Fortschritt, ganz klar,
Lasst uns gemeinsam dabei sein!

I approve the change to the apache-2.0 license.

**Comment by m-mirz** [comment]
Thanks, everyone! It looks like we have the approvals for the relevant code contributions :-)
