### ISSUE TITLE
Query:Is pandapower network to cgmes export possible using this repo

### ISSUE THREAD

**Issue by AnkurArohi** [cim-iec/cimpy#8]
I would like to know if a pandapower network saved in json or sql format can be exported to CGMES format using cimpy?

Thanks

**Comment by m-mirz** [comment]
@AnkurArohi cimpy can support this process. First, you need to generate instances of the classes found [here](https://github.com/sogno-platform/cimpy/tree/master/cimpy/cgmes_v2_4_15) from the pandapower input. Then you can use the CGMES export function.
